# Generated by Django 3.1.3 on 2021-10-11 01:21

from django.db import migrations, models
import django.utils.timezone
import django_resized.forms
import faicon.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpClases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_catogoria', models.CharField(help_text='Ingrese el nombre de la catergoria', max_length=100)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorias de ayuda del sistema',
            },
        ),
        migrations.CreateModel(
            name='HelpPost',
            fields=[
                ('id_post', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('imagen', django_resized.forms.ResizedImageField(crop=None, default='logo.png', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/website/')),
                ('titulo', models.CharField(help_text='Ingrese el título del post', max_length=50)),
                ('post', models.TextField()),
                ('autor', models.CharField(help_text='Ingrese el nombre de la/el autor', max_length=50)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug_post', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Ayuda del sistema',
            },
        ),
    ]
