# Generated by Django 3.1.3 on 2021-10-11 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppost',
            name='categoria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='help.helpclases'),
        ),
    ]
