# Generated by Django 3.1.3 on 2021-10-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_helppost_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpclases',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='helppost',
            name='id_post',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
