# Generated by Django 3.1.3 on 2021-10-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_auto_20211016_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helppost',
            name='slug_post',
        ),
    ]
