# Generated by Django 3.1.3 on 2021-10-05 12:02

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id_post', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ingrese el título del post', max_length=50)),
                ('post', tinymce.models.HTMLField()),
                ('autor', models.CharField(help_text='Ingrese el nombre de la/el autor', max_length=50)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Blog de la web',
            },
        ),
        migrations.CreateModel(
            name='Conctact',
            fields=[
                ('id_contacto', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(help_text='Ingrese el nombre de la página', max_length=50)),
                ('telefono_contacto', models.CharField(default='', help_text='Ingrese su nombre', max_length=50, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_contacto', models.EmailField(blank=True, default='', help_text='Ingrese su correo de contacto', max_length=254)),
                ('mensaje_contacto', models.TextField(help_text='Deje su mensaje aquí')),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Contactos mediante la web/app',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionWEB',
            fields=[
                ('id_configuracion', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_web_app', models.CharField(help_text='Ingrese el nombre de la web/app', max_length=50)),
                ('logo_web_app', django_resized.forms.ResizedImageField(crop=None, default='logo.png', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/website/')),
                ('localizacion', models.CharField(help_text='Ingrese la localización de su negocio', max_length=50)),
                ('email_nuevos_contactos', models.EmailField(blank=True, default='', help_text='Ingrese el correo donde recibir los nuevos contactos', max_length=254)),
                ('descripcion_web_app', models.TextField(help_text='Ingrese la descripción de la web / app para SEO')),
                ('politica_privacidad', models.TextField(help_text='Ingrese la política de privacidad de su sitio')),
                ('color_primario', colorfield.fields.ColorField(default='#FF0000', help_text='Color primario de la web', max_length=18)),
                ('color_secundario', colorfield.fields.ColorField(default='#FF0000', help_text='Color secundario de la web', max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Configuración de la web/app',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id_pagina', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_pagina', models.CharField(help_text='Ingrese el nombre de la página', max_length=50)),
                ('cuerpo_pagina', tinymce.models.HTMLField()),
                ('slug_pagina', models.CharField(blank=True, max_length=200)),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('can_delete', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Páginas de la web',
            },
        ),
    ]
