# Generated by Django 3.1.3 on 2021-10-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211005_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='can_delete',
        ),
        migrations.AddField(
            model_name='pages',
            name='pertenece_a',
            field=models.CharField(choices=[('I', 'INDEX'), ('C', 'CONTACTO'), ('B', 'BLOG'), ('O', 'OTRO')], default='O', help_text='Ingrese a que catergoria pertecene está página', max_length=1),
        ),
    ]
