# Generated by Django 3.1.3 on 2021-10-05 15:41

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20211005_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, default='logo.png', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/website/'),
        ),
        migrations.AlterField(
            model_name='conctact',
            name='telefono_contacto',
            field=models.CharField(default='', help_text='Ingrese su nombre', max_length=50, validators=[django.core.validators.RegexValidator(message="El teléfono debe de terner el formato: '+999999999'. Están permitidos hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
