# Generated by Django 3.1.3 on 2021-10-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20211005_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug_post',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
