# Generated by Django 3.1.3 on 2021-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_blog_slug_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='pertenece_a',
            field=models.CharField(choices=[('I', 'INDEX'), ('A', 'CITAS'), ('C', 'CONTACTO'), ('B', 'BLOG'), ('O', 'OTRO')], default='O', help_text='Ingrese a que catergoria pertecene está página', max_length=1),
        ),
    ]
