# Generated by Django 3.1.3 on 2021-10-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20211006_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pages',
            name='cuerpo_pagina',
            field=models.TextField(),
        ),
    ]
