from .EmailView import *
from .WhathsappView import *
from .adminView import *
from .appointmentView import *
from .authView import *
from .cashDeskView import *
from .clientView import *
from .clinicView import *
from .configView import *
from .docsView import *
from .errorsView import *
from .indexView import *
from .mapView import *
from .picturesView import *
from .portalsView import *
from .registerView import *
from .signatureView import *
from .smsView import *
from .statsView import *
from .stockView import *
from .suscriptionView import *
from .timeControlView import *
from .treatmentSessionView import *
from .treatmentView import *
from .userView import *