# Generated by Django 2.2.10 on 2020-09-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_centro', models.CharField(help_text='Enter field documentation', max_length=50)),
                ('propietaria', models.CharField(help_text='Enter field documentation', max_length=50)),
                ('localizacion', models.CharField(help_text='Enter field documentation', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Centros',
            },
        ),
        migrations.CreateModel(
            name='Potencia',
            fields=[
                ('id_potencia', models.AutoField(primary_key=True, serialize=False)),
                ('hertz', models.IntegerField(help_text='Enter field documentation', max_length=20)),
                ('milisegundos', models.IntegerField(help_text='Enter field documentation', max_length=20)),
                ('julios', models.IntegerField(help_text='Enter field documentation', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Potencias',
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id_tecnica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tecnica', models.CharField(help_text='Enter field documentation', max_length=50)),
                ('apellidos_tecnica', models.CharField(help_text='Enter field documentation', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tecnicas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(help_text='Enter field documentation', max_length=50)),
                ('apellidos_paciente', models.CharField(help_text='Enter field documentation', max_length=50)),
                ('telefono_paciente', models.IntegerField(help_text='Enter field documentation', max_length=20)),
                ('email', models.EmailField(help_text='Enter field documentation', max_length=254)),
                ('autorizacion', models.BooleanField(default=False)),
                ('protec_datos', models.BooleanField(default=False)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lima.Centro')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('zona', models.CharField(help_text='Enter field documentation', max_length=50)),
                ('comentario', models.TextField(help_text='Enter field documentation')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lima.Paciente')),
                ('potencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lima.Potencia')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lima.Tecnica')),
            ],
            options={
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
