# Generated by Django 3.1.3 on 2021-07-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='email',
            field=models.CharField(default='hola@minegocio.com', help_text='Ingrese el Email del negocio', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalconfiguracion',
            name='email',
            field=models.CharField(default='hola@minegocio.com', help_text='Ingrese el Email del negocio', max_length=100),
        ),
    ]
