# Generated by Django 3.1.3 on 2021-06-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='cliente',
            new_name='plantilla',
        ),
        migrations.RenameField(
            model_name='historicalconfiguracion',
            old_name='cliente',
            new_name='plantilla',
        ),
    ]
