# Generated by Django 3.1.3 on 2021-07-03 04:40

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsings',
            name='firma',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
