# Generated by Django 3.1.3 on 2020-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlhorario',
            name='salida',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontrolhorario',
            name='salida',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
