# Generated by Django 3.1.3 on 2021-07-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscription',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingrese la cantidad pagada por la suscripción', max_digits=20),
        ),
    ]
