# Generated by Django 2.2.10 on 2020-09-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono_paciente',
            field=models.IntegerField(help_text='Enter field documentation'),
        ),
        migrations.AlterField(
            model_name='potencia',
            name='hertz',
            field=models.IntegerField(help_text='Enter field documentation'),
        ),
        migrations.AlterField(
            model_name='potencia',
            name='julios',
            field=models.IntegerField(help_text='Enter field documentation'),
        ),
    ]
