# Generated by Django 3.1.3 on 2020-12-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0002_auto_20201212_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltecnica',
            name='imagen',
            field=models.TextField(default='img/porfile.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='imagen',
            field=models.ImageField(default='img/porfile.png', upload_to='images/'),
        ),
    ]
