# Generated by Django 3.1.3 on 2021-07-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0002_suscription_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='email_nuevos_clientes',
            new_name='enviar_email_nueva_caja',
        ),
        migrations.RenameField(
            model_name='historicalconfiguracion',
            old_name='email_nuevos_clientes',
            new_name='enviar_email_nueva_caja',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='enviar_email_nuevo_fichaje',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='enviar_email_nuevos_clientes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalconfiguracion',
            name='enviar_email_nuevo_fichaje',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalconfiguracion',
            name='enviar_email_nuevos_clientes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='email_nueva_caja',
            field=models.EmailField(default='hola@me.com', help_text='Ingrese el Email donde se enviarán los correos de nueva caja', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='email_nuevo_fichaje',
            field=models.EmailField(default='hola@me.com', help_text='Ingrese el Email donde se enviarán los correos de nuevos fichajes', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracion',
            name='email_nueva_caja',
            field=models.EmailField(default='hola@me.com', help_text='Ingrese el Email donde se enviarán los correos de nueva caja', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracion',
            name='email_nuevo_fichaje',
            field=models.EmailField(default='hola@me.com', help_text='Ingrese el Email donde se enviarán los correos de nuevos fichajes', max_length=100),
        ),
    ]
