# Generated by Django 3.1.3 on 2021-07-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0002_auto_20210704_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id_sicription', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_suscription', models.CharField(help_text='Ingrese el nombre de la suscripción', max_length=100)),
                ('coments_suscription', models.TextField(help_text='Comentarios de la suscripción')),
                ('stardate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False)),
            ],
        ),
    ]
