# Generated by Django 3.1.3 on 2021-06-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0002_auto_20210629_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='id_paciente',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_paciente',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
