# Generated by Django 2.2.10 on 2020-09-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0002_auto_20200901_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potencia',
            name='milisegundos',
            field=models.IntegerField(help_text='Enter field documentation'),
        ),
    ]
