# Generated by Django 3.1.3 on 2021-07-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0002_auto_20210703_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsings',
            name='base64',
            field=models.FileField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
