# Generated by Django 2.2.10 on 2020-09-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0003_auto_20200901_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnica',
            options={'verbose_name_plural': 'Tecnicas | Tecnicos'},
        ),
        migrations.AlterField(
            model_name='centro',
            name='localizacion',
            field=models.CharField(help_text='Ingrese la hubicación del centro', max_length=100),
        ),
        migrations.AlterField(
            model_name='centro',
            name='nombre_centro',
            field=models.CharField(help_text='Ingrese el nombre del centro', max_length=50),
        ),
        migrations.AlterField(
            model_name='centro',
            name='propietaria',
            field=models.CharField(help_text='Ingrese el nombre de la/el propietari@', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='comentario',
            field=models.TextField(help_text='Ingrese los comentarios sobre la cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='zona',
            field=models.CharField(help_text='Ingrese la zona tratada o por tratar', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos_paciente',
            field=models.CharField(help_text='Ingrese los apellidos de la/el paciente', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(help_text='Ingrese el correo electronico de la/el paciente', max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_paciente',
            field=models.CharField(help_text='Ingrese el nombre de la/el paciente', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_paciente',
            field=models.IntegerField(help_text='Ingrese el teléfono de la/el paciente'),
        ),
        migrations.AlterField(
            model_name='potencia',
            name='hertz',
            field=models.IntegerField(help_text='Ingrese la potencia en hertz'),
        ),
        migrations.AlterField(
            model_name='potencia',
            name='julios',
            field=models.IntegerField(help_text='Ingrese la potencia en julios'),
        ),
        migrations.AlterField(
            model_name='potencia',
            name='milisegundos',
            field=models.IntegerField(help_text='Ingrese la potencia en milisegundos'),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='apellidos_tecnica',
            field=models.CharField(help_text='Ingrese los apellidos de la/el tecnic@', max_length=50),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='nombre_tecnica',
            field=models.CharField(help_text='Ingrese el nombre de la/el tecnic@', max_length=50),
        ),
    ]
