# Generated by Django 3.1.3 on 2021-07-03 04:52

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0003_auto_20210703_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsings',
            name='base64',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
    ]
