# Generated by Django 3.1.3 on 2021-07-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0003_suscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscription',
            name='type',
            field=models.CharField(choices=[('S', 'Suscripción'), ('E', 'Extras'), ('O', 'Otras')], default='S', max_length=1),
        ),
    ]
