# Generated by Django 3.1.3 on 2021-06-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0003_auto_20210629_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='plantilla',
            new_name='plantilla_email',
        ),
        migrations.RenameField(
            model_name='historicalconfiguracion',
            old_name='plantilla',
            new_name='plantilla_email',
        ),
    ]
