# Generated by Django 2.2.10 on 2020-09-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0004_auto_20200901_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(default='Valencia', help_text='Ingrese la dirección del/la paciente', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='poblacion',
            field=models.CharField(default='Valencia', help_text='Ingrese la población del/la paciente', max_length=50),
        ),
        migrations.AlterField(
            model_name='centro',
            name='id_centro',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_cita',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_paciente',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='potencia',
            name='id_potencia',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='id_tecnica',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
