# Generated by Django 3.1.3 on 2021-07-10 19:07

from django.db import migrations
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0005_auto_20210710_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='centro',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='controlhorario',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='docsings',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctemplate',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtemplates',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcentro',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcita',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracion',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcontrolhorario',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldoctemplate',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalemailtemplates',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaltecnica',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalturnos',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lista',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, default='', max_length=50),
        ),
    ]
