# Generated by Django 3.1.3 on 2021-07-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0006_auto_20210710_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='comentario',
            field=models.CharField(blank=True, default='', help_text='Ingrese el comentario de la caja', max_length=100),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='comentario',
            field=models.CharField(blank=True, help_text='Ingrese el comentario del tratamiento', max_length=100),
        ),
    ]
