# Generated by Django 3.1.3 on 2021-07-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0007_auto_20210713_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientos',
            name='numero_de_sesion',
            field=models.IntegerField(default=1, help_text='Ingrese el número de sesión del tratamiento'),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='zona',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.servicios'),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='fecha',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
