# Generated by Django 3.1.3 on 2021-07-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0008_auto_20210713_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='dni',
            field=models.CharField(blank=True, default='', help_text='Ingrese el DNI del cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='email',
            field=models.EmailField(blank=True, help_text='Ingrese el correo electronico de la/el paciente', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='telefono_paciente',
            field=models.IntegerField(blank=True, help_text='Ingrese el teléfono de la/el paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(blank=True, default='', help_text='Ingrese el DNI del cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, help_text='Ingrese el correo electronico de la/el paciente', max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_paciente',
            field=models.IntegerField(blank=True, help_text='Ingrese el teléfono de la/el paciente'),
        ),
    ]
