# Generated by Django 3.1.3 on 2021-07-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0012_auto_20210713_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='telefono_paciente',
            field=models.IntegerField(default=0, help_text='Ingrese el teléfono de la/el paciente', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_paciente',
            field=models.IntegerField(default=0, help_text='Ingrese el teléfono de la/el paciente', null=True),
        ),
    ]
