# Generated by Django 3.1.3 on 2021-07-14 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0014_auto_20210713_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientos',
            name='hora_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
