# Generated by Django 3.1.3 on 2021-07-22 22:28

from django.db import migrations, models
import django.db.models.deletion
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0015_tratamientos_hora_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesClientes',
            fields=[
                ('id_image_cliente', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='images/clientes/')),
                ('comentario', models.CharField(blank=True, default='', help_text='Ingrese el comentario de la imágen', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lima.paciente')),
                ('tecnica', models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.tecnica')),
            ],
            options={
                'verbose_name_plural': 'Listas de imágenes de clientes',
            },
        ),
    ]
