# Generated by Django 3.1.3 on 2021-07-23 00:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0016_imagenesclientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesclientes',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/clientes/'),
        ),
    ]
