# Generated by Django 3.1.3 on 2021-07-23 00:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0017_auto_20210723_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, default='img/login.png', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, default='img/porfile.png', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/'),
        ),
    ]
