# Generated by Django 3.1.3 on 2021-08-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0018_auto_20210723_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='telefono_centro',
            field=models.IntegerField(blank=True, default=0, help_text='Ingrese el teléfono del centro', null=True),
        ),
        migrations.AddField(
            model_name='historicalcentro',
            name='telefono_centro',
            field=models.IntegerField(blank=True, default=0, help_text='Ingrese el teléfono del centro', null=True),
        ),
    ]
