# Generated by Django 3.1.3 on 2021-09-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0020_auto_20210826_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='mailchimp_api_key',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='mailchimp_list_id',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='mailchimp_server',
        ),
        migrations.RemoveField(
            model_name='historicalconfiguracion',
            name='mailchimp_api_key',
        ),
        migrations.RemoveField(
            model_name='historicalconfiguracion',
            name='mailchimp_list_id',
        ),
        migrations.RemoveField(
            model_name='historicalconfiguracion',
            name='mailchimp_server',
        ),
    ]
