# Generated by Django 3.1.3 on 2021-09-07 20:56

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import faicon.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lima', '0021_auto_20210906_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(help_text='Ingrese el nombre del estado', max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FF0000', help_text='Color del estado', max_length=18)),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estados del sistema',
            },
        ),
        migrations.CreateModel(
            name='Paneles',
            fields=[
                ('id_panel', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_panel', models.CharField(help_text='Ingrese el nombre del estado', max_length=50)),
                ('descripcion_panel', models.TextField(help_text='Ingrese la descripción del panel')),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Paneles del sistema',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id_tag', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_etiqueta', models.CharField(help_text='Ingrese el nombre de la etiqueta', max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FF0000', help_text='Color de la etiqueta', max_length=18)),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Etiquetas del sistema',
            },
        ),
        migrations.AddField(
            model_name='centro',
            name='horario_apertura_entre_semana',
            field=models.TimeField(default='09:00:00', help_text='Ingrese la hora de apertura de la clínica entre semana'),
        ),
        migrations.AddField(
            model_name='centro',
            name='horario_apertura_fin_semana',
            field=models.TimeField(default='09:00:00', help_text='Ingrese la hora de apertura de la clínica el fin de semana'),
        ),
        migrations.AddField(
            model_name='centro',
            name='horario_cierre_entre_semana',
            field=models.TimeField(default='21:00:00', help_text='Ingrese la hora de cierre de la clínica entre semana'),
        ),
        migrations.AddField(
            model_name='centro',
            name='horario_cierre_fin_semana',
            field=models.TimeField(default='21:00:00', help_text='Ingrese la hora de apertura de la clínica el fin de semana'),
        ),
        migrations.AddField(
            model_name='historicalcentro',
            name='horario_apertura_entre_semana',
            field=models.TimeField(default='09:00:00', help_text='Ingrese la hora de apertura de la clínica entre semana'),
        ),
        migrations.AddField(
            model_name='historicalcentro',
            name='horario_apertura_fin_semana',
            field=models.TimeField(default='09:00:00', help_text='Ingrese la hora de apertura de la clínica el fin de semana'),
        ),
        migrations.AddField(
            model_name='historicalcentro',
            name='horario_cierre_entre_semana',
            field=models.TimeField(default='21:00:00', help_text='Ingrese la hora de cierre de la clínica entre semana'),
        ),
        migrations.AddField(
            model_name='historicalcentro',
            name='horario_cierre_fin_semana',
            field=models.TimeField(default='21:00:00', help_text='Ingrese la hora de apertura de la clínica el fin de semana'),
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='notas_paciente',
            field=models.TextField(blank=True, default='', help_text='Ingrese notas sobre el cliente aquí'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='notas_paciente',
            field=models.TextField(blank=True, default='', help_text='Ingrese notas sobre el cliente aquí'),
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id_mensaje', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cuerpo_mensaje', models.TextField(help_text='Ingrese la descripción aquí')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lima.tecnica')),
            ],
            options={
                'verbose_name_plural': 'Paneles del sistema',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTags',
            fields=[
                ('id_tag', models.IntegerField(auto_created=True, blank=True, db_index=True)),
                ('nombre_etiqueta', models.CharField(help_text='Ingrese el nombre de la etiqueta', max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FF0000', help_text='Color de la etiqueta', max_length=18)),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaneles',
            fields=[
                ('id_panel', models.IntegerField(auto_created=True, blank=True, db_index=True)),
                ('nombre_panel', models.CharField(help_text='Ingrese el nombre del estado', max_length=50)),
                ('descripcion_panel', models.TextField(help_text='Ingrese la descripción del panel')),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical paneles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMensajes',
            fields=[
                ('id_mensaje', models.IntegerField(auto_created=True, blank=True, db_index=True)),
                ('cuerpo_mensaje', models.TextField(help_text='Ingrese la descripción aquí')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('enviado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lima.tecnica')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mensajes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEstados',
            fields=[
                ('id_estado', models.IntegerField(auto_created=True, blank=True, db_index=True)),
                ('nombre_estado', models.CharField(help_text='Ingrese el nombre del estado', max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FF0000', help_text='Color del estado', max_length=18)),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical estados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        # migrations.AddField(
        #     model_name='historicalpaciente',
        #     name='estado_paciente',
        #     field=models.ForeignKey(blank=True, db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lima.estados'),
        # ),
        # migrations.AddField(
        #     model_name='paciente',
        #     name='estado_paciente',
        #     field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.estados'),
        # ),
    ]
