# Generated by Django 3.1.3 on 2021-09-07 20:59

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import faicon.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lima', '0022_auto_20210907_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosClientes',
            fields=[
                ('id_estado', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(help_text='Ingrese el nombre del estado', max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FF0000', help_text='Color del estado', max_length=18)),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estados del sistema',
            },
        ),
        migrations.AddField(
            model_name='estados',
            name='enviado_por',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.paneles'),
        ),
        migrations.AddField(
            model_name='historicalestados',
            name='enviado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lima.paneles'),
        ),
        migrations.CreateModel(
            name='HistoricalEstadosClientes',
            fields=[
                ('id_estado', models.IntegerField(auto_created=True, blank=True, db_index=True)),
                ('nombre_estado', models.CharField(help_text='Ingrese el nombre del estado', max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FF0000', help_text='Color del estado', max_length=18)),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical estados clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        # migrations.AlterField(
        #     model_name='historicalpaciente',
        #     name='estado_paciente',
        #     field=models.ForeignKey(blank=True, db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lima.estadosclientes'),
        # ),
        # migrations.AlterField(
        #     model_name='paciente',
        #     name='estado_paciente',
        #     field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.estadosclientes'),
        # ),
    ]
