# Generated by Django 3.1.3 on 2021-09-08 00:09

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0024_auto_20210907_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estados',
            old_name='enviado_por',
            new_name='panel',
        ),
        migrations.AddField(
            model_name='estados',
            name='centro',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.centro'),
        ),
        migrations.AddField(
            model_name='tags',
            name='centro',
            field=models.ManyToManyField(default='1', to='lima.Centro'),
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id_tarea', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_tarea', models.CharField(help_text='Ingrese el nombre del estado', max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FF0000', help_text='Color del estado', max_length=18)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon', faicon.fields.FAIconField(blank=True, default='', max_length=50)),
                ('estado', models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.estados')),
                ('propietario', models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.tecnica')),
            ],
            options={
                'verbose_name_plural': 'Tareas del sistema',
            },
        ),
        migrations.AddField(
            model_name='historicalmensajes',
            name='tarea',
            field=models.ForeignKey(blank=True, db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lima.tareas'),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='tarea',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.tareas'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tarea',
            field=models.ManyToManyField(default='1', to='lima.Tareas'),
        ),
    ]
