# Generated by Django 3.1.3 on 2021-09-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0025_auto_20210908_0009'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='historicalpaciente',
        #     name='estado_paciente',
        # ),
        # migrations.RemoveField(
        #     model_name='paciente',
        #     name='estado_paciente',
        # ),
    ]
