# Generated by Django 3.1.3 on 2021-09-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0026_auto_20210908_0031'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='historicalpaciente',
        #     name='estado_paciente',
        #     field=models.ForeignKey(blank=True, db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lima.estadosclientes'),
        # ),
        # migrations.AddField(
        #     model_name='paciente',
        #     name='estado_paciente',
        #     field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.estadosclientes'),
        # ),
    ]
