# Generated by Django 3.1.3 on 2021-09-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0027_auto_20210908_0049'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='historicalpaciente',
        #     name='estado_paciente',
        # ),
        # migrations.RemoveField(
        #     model_name='paciente',
        #     name='estado_paciente',
        # ),
        # migrations.AddField(
        #     model_name='paciente',
        #     name='estado_paciente',
        #     field=models.ManyToManyField(default='1', to='lima.EstadosClientes'),
        # ),
    ]
