# Generated by Django 3.1.3 on 2021-09-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0028_auto_20210908_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.ManyToManyField(default='1', to='lima.EstadosClientes'),
        ),
    ]
