# Generated by Django 3.1.3 on 2021-09-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0029_paciente_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadosclientes',
            options={'verbose_name_plural': 'Estados de clientes'},
        ),
    ]
