# Generated by Django 3.1.3 on 2021-09-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0031_auto_20210908_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tarea',
            field=models.ManyToManyField(blank=True, default='1', to='lima.Tareas'),
        ),
    ]
