# Generated by Django 3.1.3 on 2021-09-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0032_auto_20210908_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='etiqueta',
            field=models.ManyToManyField(default='1', to='lima.Tareas'),
        ),
    ]
