# Generated by Django 3.1.3 on 2021-09-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0033_paciente_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='etiqueta',
            field=models.ManyToManyField(default='1', to='lima.Tags'),
        ),
    ]
