# Generated by Django 3.1.3 on 2021-09-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0035_auto_20210908_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='etiqueta',
            field=models.ManyToManyField(blank=True, default='1', to='lima.Tags'),
        ),
    ]
