# Generated by Django 3.1.3 on 2021-09-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0036_auto_20210908_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnica',
            name='portales',
            field=models.ManyToManyField(blank=True, default='1', related_name='portales', to='lima.Centro'),
        ),
    ]
