# Generated by Django 3.1.3 on 2021-09-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0037_tecnica_portales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnica',
            name='portales',
            field=models.ManyToManyField(blank=True, default='1', related_name='portales', to='lima.Paneles'),
        ),
    ]
