# Generated by Django 3.1.3 on 2021-09-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0038_auto_20210908_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='descripcion_tarea',
            field=models.TextField(blank=True, default='', help_text='Ingrese la descripción de la tarea'),
        ),
    ]
