# Generated by Django 3.1.3 on 2021-09-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0039_tareas_descripcion_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados',
            name='orden_del_estado',
            field=models.IntegerField(default=0, help_text='Ingrese el orden a aplicar'),
        ),
    ]
