# Generated by Django 3.1.3 on 2021-09-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0043_auto_20210909_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='fecha_nacimiento',
            field=models.DateTimeField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
