# Generated by Django 3.1.3 on 2021-09-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0046_anuncios_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='cuerpo_anuncio',
            field=models.CharField(help_text='Ingrese el nombre del estado', max_length=50),
        ),
    ]
