# Generated by Django 3.1.3 on 2021-09-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0047_auto_20210910_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='cuerpo_anuncio',
            field=models.CharField(help_text='Ingrese el nombre del estado', max_length=100),
        ),
    ]
