# Generated by Django 3.1.3 on 2021-09-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0048_auto_20210910_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncios',
            name='link_anuncio',
            field=models.CharField(blank=True, default='', help_text='Ingrese el link del anuncio', max_length=10000),
        ),
        migrations.AlterField(
            model_name='anuncios',
            name='cuerpo_anuncio',
            field=models.CharField(help_text='Ingrese el anuncio', max_length=100),
        ),
    ]
