# Generated by Django 3.1.3 on 2021-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0050_auto_20210910_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.ManyToManyField(default='Nuevo', to='lima.EstadosClientes'),
        ),
    ]
