# Generated by Django 3.1.3 on 2021-09-25 16:01

from django.db import migrations, models
import lima.models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0052_auto_20210925_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.ManyToManyField(blank=True, default=lima.models.allEstados, to='lima.EstadosClientes'),
        ),
    ]
