# Generated by Django 3.1.3 on 2021-09-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0053_auto_20210925_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='estado',
            field=models.ForeignKey(blank=True, db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lima.estadosclientes'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='estado',
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='lima.estadosclientes'),
        ),
    ]
