# Generated by Django 3.1.3 on 2021-09-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0055_auto_20210925_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaciente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='estado',
        ),
    ]
