# Generated by Django 3.1.3 on 2021-09-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0057_auto_20210925_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='twilio_ACCOUNT_SID',
            field=models.CharField(default='', help_text='Ingrese la ACCOUNT SID de Twilio', max_length=500),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='twilio_AUTH_TOKEN',
            field=models.CharField(default='', help_text='Ingrese el AUTH TOKEN de Twilio', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalconfiguracion',
            name='twilio_ACCOUNT_SID',
            field=models.CharField(default='', help_text='Ingrese la ACCOUNT SID de Twilio', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalconfiguracion',
            name='twilio_AUTH_TOKEN',
            field=models.CharField(default='', help_text='Ingrese el AUTH TOKEN de Twilio', max_length=500),
        ),
    ]
