# Generated by Django 3.1.3 on 2021-09-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0058_auto_20210926_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='twilio_NUMBER',
            field=models.IntegerField(default=0, help_text='Ingrese el Número verificado en Twilio', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalconfiguracion',
            name='twilio_NUMBER',
            field=models.IntegerField(default=0, help_text='Ingrese el Número verificado en Twilio', max_length=500),
        ),
    ]
