# Generated by Django 3.1.3 on 2021-09-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0061_auto_20210926_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='twilio_SENDGRID_API_KEY',
            field=models.CharField(default='', help_text='Ingrese la SENDGRID API KEY de Twilio', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalconfiguracion',
            name='twilio_SENDGRID_API_KEY',
            field=models.CharField(default='', help_text='Ingrese la SENDGRID API KEY de Twilio', max_length=500),
        ),
    ]
