# Generated by Django 3.1.3 on 2021-09-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0063_auto_20210927_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='enviar_email_nueva_caja',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='enviar_email_nuevas_listas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='enviar_email_nuevo_fichaje',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='enviar_email_nuevos_clientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='plantilla_email',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, related_name='plantilla_email', to='lima.emailtemplates'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='plantilla_lista',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, related_name='plantilla_lista', to='lima.emailtemplates'),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracion',
            name='enviar_email_nueva_caja',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracion',
            name='enviar_email_nuevas_listas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracion',
            name='enviar_email_nuevo_fichaje',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracion',
            name='enviar_email_nuevos_clientes',
            field=models.BooleanField(default=False),
        ),
    ]
