# Generated by Django 3.1.3 on 2021-10-06 12:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0064_auto_20210927_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='dias_abre_centro',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], default='lunes', max_length=52),
        ),
        migrations.AddField(
            model_name='historicalcentro',
            name='dias_abre_centro',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], default='lunes', max_length=52),
        ),
    ]
