# Generated by Django 3.1.3 on 2021-10-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0065_auto_20211006_1206'),
    ]

    operations = [

    ]
