# Generated by Django 3.1.3 on 2021-10-06 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0067_auto_20211006_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTurnos',
        ),
    ]
