# Generated by Django 3.1.3 on 2021-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0068_delete_historicalturnos'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='turnos',
    #         old_name='turno',
    #         new_name='turno_inicio',
    #     ),
    #     migrations.AddField(
    #         model_name='turnos',
    #         name='turno_fin',
    #         field=models.DateTimeField(default='2021-10-01 00:00:00'),
    #     ),
    #]
