# Generated by Django 3.1.3 on 2021-10-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0069_auto_20211006_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='turno',
        ),
        migrations.AddField(
            model_name='turnos',
            name='turno_fin',
            field=models.DateTimeField(default='2021-10-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='turno_inicio',
            field=models.DateTimeField(default='2021-10-01 01:00:00'),
        ),
    ]
