# Generated by Django 3.1.3 on 2021-10-11 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0085_auto_20211011_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='turno_fin',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 1, 21, 11, 796829)),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='turno_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 1, 21, 11, 796829)),
        ),
    ]
