# Generated by Django 3.1.3 on 2021-10-11 02:20

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0089_auto_20211011_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, default='img/porfile.png', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/'),
        ),
        migrations.AddField(
            model_name='historicalcentro',
            name='imagen',
            field=models.TextField(default='img/porfile.png', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='imagen',
            field=models.TextField(default='img/porfile.png', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, default='img/porfile.png', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/'),
        ),
    ]
