# Generated by Django 3.1.3 on 2021-10-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0090_auto_20211011_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='descripcion_tarea',
            field=models.TextField(blank=True, default='', help_text='Ingrese la descripción de la tarea'),
        ),
    ]
