# Generated by Django 3.1.3 on 2021-10-16 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0092_auto_20211016_0037'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='HistoricalPaciente',
    #     ),
    #]
