# Generated by Django 3.1.3 on 2021-10-16 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0093_delete_historicalpaciente'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='historicalcita',
        #     name='history_user',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalcita',
        #     name='paciente',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalcita',
        #     name='tecnica',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalcita',
        #     name='zona',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalconfiguracion',
        #     name='history_user',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalconfiguracion',
        #     name='plantilla_email',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalconfiguracion',
        #     name='plantilla_lista',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalcontrolhorario',
        #     name='history_user',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalcontrolhorario',
        #     name='tecnica',
        # ),
        # migrations.RemoveField(
        #     model_name='historicaldoctemplate',
        #     name='history_user',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalemailtemplates',
        #     name='history_user',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalmensajes',
        #     name='enviado_por',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalmensajes',
        #     name='history_user',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalmensajes',
        #     name='tarea',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalpaciente',
        #     name='centro',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalpaciente',
        #     name='estado',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalpaciente',
        #     name='history_user',
        # ),
        # migrations.RemoveField(
        #     model_name='historicaltags',
        #     name='history_user',
        # ),
        # migrations.RemoveField(
        #     model_name='historicaltecnica',
        #     name='history_user',
        # ),
        # migrations.RemoveField(
        #     model_name='historicaltecnica',
        #     name='user',
        # ),
        migrations.AlterField(
            model_name='configuracion',
            name='twilio_NUMBER',
            field=models.CharField(blank=True, default=0, help_text='Ingrese el Número verificado en Twilio', max_length=17, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el siguiente formato: '+999999999'. Están permidos hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Ingrese el correo electronico de la/el paciente', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_paciente',
            field=models.CharField(blank=True, default=0, help_text='Ingrese el teléfono de la/el paciente', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el siguiente formato: '+999999999'. Están permidos hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.DeleteModel(
            name='HistoricalCentro',
        ),
        migrations.DeleteModel(
            name='HistoricalCita',
        ),
        migrations.DeleteModel(
            name='HistoricalConfiguracion',
        ),
        migrations.DeleteModel(
            name='HistoricalControlHorario',
        ),
        migrations.DeleteModel(
            name='HistoricalDocTemplate',
        ),
        migrations.DeleteModel(
            name='HistoricalEmailTemplates',
        ),
        migrations.DeleteModel(
            name='HistoricalMensajes',
        ),
        # migrations.DeleteModel(
        #     name='HistoricalPaciente',
        # ),
        migrations.DeleteModel(
            name='HistoricalTags',
        ),
        migrations.DeleteModel(
            name='HistoricalTecnica',
        ),
    ]
