# Generated by Django 3.1.3 on 2021-10-20 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0095_auto_20211016_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Ingrese el correo electronico de la/el paciente', max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_paciente',
            field=models.CharField(blank=True, default=0, help_text='Ingrese el teléfono de la/el paciente', max_length=17, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el siguiente formato: '+999999999'. Están permidos hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
