# Generated by Django 3.1.3 on 2021-10-20 17:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0096_auto_20211020_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='imagen',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='img/porfile.png', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/'),
        ),
    ]
