# Generated by Django 3.1.3 on 2021-10-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0098_auto_20211020_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, default='Valencia', help_text='Ingrese la dirección del/la paciente', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='poblacion',
            field=models.CharField(blank=True, default='Valencia', help_text='Ingrese la población del/la paciente', max_length=50),
        ),
    ]
