# Generated by Django 3.1.3 on 2021-10-20 23:18

from django.db import migrations, models
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0099_auto_20211020_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientos',
            name='firma',
            field=jsignature.fields.JSignatureField(blank=True, default='Firma aquí', null=True),
        ),
        migrations.AddField(
            model_name='tratamientos',
            name='firma_imagen',
            field=models.CharField(default='', help_text='Ingrese la url de la firma', max_length=100),
        ),
    ]
