# Generated by Django 3.1.3 on 2021-10-22 10:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0101_auto_20211022_0908'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='docsings',
        #     name='firma_imagen',
        # ),
        # migrations.RemoveField(
        #     model_name='docsings',
        #     name='imagen',
        # ),
        migrations.AlterField(
            model_name='docsings',
            name='firma',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/signatures'),
        ),
    ]
