# Generated by Django 3.1.3 on 2021-10-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0103_auto_20211022_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsings',
            name='plantilla_render',
        ),
    ]
