# Generated by Django 3.1.3 on 2021-10-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0104_remove_docsings_plantilla_render'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctemplate',
            name='plantilla_doc',
            field=models.TextField(help_text='Configure su plantilla'),
        ),
    ]
