# Generated by Django 3.1.3 on 2021-10-23 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0105_auto_20211022_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsings',
            name='firma_imagen',
        ),
        migrations.RemoveField(
            model_name='docsings',
            name='imagen',
        ),
    ]
