# Generated by Django 3.1.3 on 2021-10-25 10:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0107_anuncios_todos_los_centros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamientos',
            name='firma_imagen',
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='firma',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/signatures/'),
        ),
    ]
