# Generated by Django 3.1.3 on 2021-10-25 10:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0108_auto_20211025_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientos',
            name='firma',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='PNG', keep_meta=True, quality=75, size=[500, 500], upload_to='images/signatures/'),
        ),
    ]
