# Generated by Django 3.1.3 on 2021-11-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0112_remove_configuracion_enviar_email_nuevo_fichaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='enviar_email_nuevo_fichaje',
            field=models.BooleanField(default=False),
        ),
    ]
