# Generated by Django 3.1.3 on 2021-11-07 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0114_auto_20211107_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='autorizacion_envio_informacion_comercial',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, default='Valencia', help_text='Ingrese la dirección del/la paciente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lima.estadosclientes'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='etiqueta',
            field=models.ManyToManyField(blank=True, default='1', null=True, to='lima.Tags'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='notas_paciente',
            field=models.TextField(blank=True, default='', help_text='Ingrese notas sobre el cliente aquí', null=True),
        ),
        # migrations.AlterField(
        #     model_name='paciente',
        #     name='origen_id',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lima.origenes'),
        # ),
        migrations.AlterField(
            model_name='paciente',
            name='poblacion',
            field=models.CharField(blank=True, default='Valencia', help_text='Ingrese la población del/la paciente', max_length=50, null=True),
        ),
    ]
