# Generated by Django 3.1.3 on 2021-11-08 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lima', '0116_auto_20211108_2133'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Origenes',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
        #         ('origen', models.CharField(help_text='Ingrese el nombre del servicio', max_length=100)),
        #         ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
        #     ],
        #     options={
        #         'verbose_name_plural': 'Origenes',
        #     },
        # ),
        migrations.AddField(
            model_name='configuracion',
            name='numero_citas',
            field=models.IntegerField(default='1', help_text='Ingrese la cantidad de citas que se pueden agendar por el módulo online'),
        ),
        # migrations.AddField(
        #     model_name='paciente',
        #     name='origen',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lima.origenes'),
        # ),
    ]
